import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.interactions.Actions;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import java.util.HashMap;
import java.util.Map;

public class AccountCreationSteps {
    private WebDriver driver;

    @Given("I use {string}")
    public void iUse(String browser) {
        if (browser.equals("Google Chrome")) {
            driver = new ChromeDriver();
        } else if (browser.equals("Microsoft Edge")) {
            driver = new EdgeDriver();
        } else {
            fail("Invalid browser");
        }
    }

    @And("I browse to Basketball England membership")
    public void iBrowseToBasketballEnglandMembership() {
        driver.get("https://membership.basketballengland.co.uk/NewSupporterAccount");
    }

    @And("I have entered {string} as valid date of birth")
    public void iHaveEnteredAsValidDateOfBirth(String date) {
        driver.findElement(By.id("dp")).click();
        driver.findElement(By.id("dp")).sendKeys(date);

        new Actions(driver)
                .sendKeys(Keys.ESCAPE)
                .perform();
    }

    @And("I have entered {string} as first name")
    public void iHaveEnteredAsFirstName(String firstName) {
        driver.findElement(By.id("member_firstname")).click();
        driver.findElement(By.id("member_firstname")).sendKeys(firstName);
    }

    @And("I have entered {string} as last name")
    public void iHaveEnteredAsLastName(String lastName) {
        driver.findElement(By.id("member_lastname")).click();
        driver.findElement(By.id("member_lastname")).sendKeys(lastName);
    }

    @And("I have entered {string} as email address")
    public void iHaveEnteredAsEmailAddress(String email) {
        driver.findElement(By.id("member_emailaddress")).click();
        driver.findElement(By.id("member_emailaddress")).sendKeys(email);
    }

    @And("I have entered {string} as confirm email address")
    public void iHaveEnteredAsConfirmEmailAddress(String confirmEmail) {
        driver.findElement(By.id("member_confirmemailaddress")).click();
        driver.findElement(By.id("member_confirmemailaddress")).sendKeys(confirmEmail);
    }

    @And("I have entered {string} as password")
    public void iHaveEnteredAsPassword(String password) {
        driver.findElement(By.id("signupunlicenced_password")).click();
        driver.findElement(By.id("signupunlicenced_password")).sendKeys(password);
    }

    @And("I have entered {string} as retype your password")
    public void iHaveEnteredAsRetypeYourPassword(String confirmPassword) {
        driver.findElement(By.id("signupunlicenced_confirmpassword")).click();
        driver.findElement(By.id("signupunlicenced_confirmpassword")).sendKeys(confirmPassword);
    }

    @And("I have checked Terms and Conditions")
    public void iHaveCheckedTermsAndConditions() {
        driver.findElement(By.cssSelector(".md-checkbox > .md-checkbox:nth-child(1) .box")).click();
    }

    @And("I have checked age control and code of conduct")
    public void iHaveCheckedAgeControlAndCodeOfConduct() {
        driver.findElement(By.cssSelector(".md-checkbox:nth-child(2) > label > .box")).click();
        driver.findElement(By.cssSelector(".md-checkbox:nth-child(7) .box")).click();
    }

    @When("I click Confirm and Join")
    public void iClickConfirmAndJoin() {
        driver.findElement(By.name("join")).click();
    }

    @Then("The membership is created")
    public void theMembershipIsCreated() {
        WebElement field = driver.findElement(By.xpath("/html/body/div/div[2]/div/h2"));
        String expected = "THANK YOU FOR CREATING AN ACCOUNT WITH BASKETBALL ENGLAND";
        String actual = field.getText();
        assertEquals(expected, actual);

        driver.close();
    }
}


/*
package Selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
        import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
        import java.net.MalformedURLException;
import java.net.URL;
public class TESTCREATEANACCOUNT10Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void tESTCREATEANACCOUNT10() {
        driver.get("https://membership.basketballengland.co.uk/NewSupporterAccount");
        driver.manage().window().setSize(new Dimension(1936, 1168));
        driver.findElement(By.id("dp")).click();
        driver.findElement(By.id("dp")).sendKeys("01/04/1990");
        driver.findElement(By.id("member_firstname")).click();
        driver.findElement(By.id("member_firstname")).sendKeys("Peter");
        driver.findElement(By.id("member_lastname")).click();
        driver.findElement(By.id("member_lastname")).sendKeys("Parker");
        driver.findElement(By.id("member_emailaddress")).click();
        driver.findElement(By.id("member_emailaddress")).sendKeys("peterparker@gmail.123.com");
        driver.findElement(By.id("member_confirmemailaddress")).click();
        driver.findElement(By.id("member_confirmemailaddress")).sendKeys("peterparker@gmail.123.com");
        driver.findElement(By.id("signupunlicenced_password")).click();
        driver.findElement(By.id("signupunlicenced_password")).sendKeys("123asd");
        driver.findElement(By.id("signupunlicenced_confirmpassword")).click();
        driver.findElement(By.id("signupunlicenced_confirmpassword")).sendKeys("123asd");
        driver.findElement(By.cssSelector(".md-checkbox > .md-checkbox:nth-child(1) .box")).click();
        driver.findElement(By.cssSelector(".md-checkbox:nth-child(2) > label > .box")).click();
        driver.findElement(By.cssSelector(".md-checkbox:nth-child(7) .box")).click();
        driver.findElement(By.name("join")).click();
        driver.close();
    }
}
*/
